# Server configuration
server:
  port: 8092

# Spring boot application name    
#DEV the oracle configuration
spring:
  application:
    name: usman-account-mgmt
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  datasource: 
      url: jdbc:oracle:thin:@10.1.13.182:1521:CEBS
      username: usmanib
      password: usmanib
      driver-class-name: oracle.jdbc.OracleDriver
 
#Eureka client setup     
eureka:
  client:
    serviceUrl:
      #defaultZone: http://10.7.91.40:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
